// <auto-generated />
namespace Seed.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Somethingchanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Somethingchanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201405291948431_Something changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
