// <auto-generated />
namespace Seed.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Userstate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Userstate));
        
        string IMigrationMetadata.Id
        {
            get { return "201407202016363_User state"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
