// <auto-generated />
namespace Seed.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Tempremovalofregistrationtokens : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tempremovalofregistrationtokens));
        
        string IMigrationMetadata.Id
        {
            get { return "201405262039319_Temp removal of registration tokens"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
