// <auto-generated />
namespace Seed.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Concurrency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Concurrency));
        
        string IMigrationMetadata.Id
        {
            get { return "201405030546322_Concurrency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
